model:
  base_learning_rate: 1.0e-05
  target: model.WrapperLightningModule
  params:
    local_cache_dir: weights
    
    



    
data:
  target: src.data.building_texture.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 8
    train:
      target: src.data.building_texture.ObjaverseData
      params:
        root_dir: data/building_texture_mask
        meta_fname: texture_refence.json
        input_image_dir: normals
        ref_dir: ref_crops
        rgb_dir: rgb_images
        img_size: 768
        num_ref: 3
        validation: false
    validation:
      target: src.data.building_texture.ValidationData
      params:
        root_dir: data/building_texture_mask/valid_samples
        input_image_size: 768



lightning:
  modelcheckpoint:
    params:
      every_n_train_steps: 2000
      save_top_k: -1
      save_last: true
  callbacks: {}

  trainer:
    benchmark: true
    max_epochs: -1
    val_check_interval: 1000
    num_sanity_val_steps: 0
    accumulate_grad_batches: 8
    check_val_every_n_epoch: null   # if not set this, validation does not run
